package com.clearcaptions.transport;

public enum PhoneEvent {
	PHONE_NORMAL,
	PHONE_CALL_WAITING,
	PHONE_ON_HOLD,
	PHONE_3WAY_CALL,
	PHONE_LOCAL_SPEAKING,
	PHONE_LOCAL_SPEAKING_STOPPED,
	PHONE_REMOTE_SPEAKING,
	PHONE_REMOTE_SPEAKING_STOPPED
}
